### ISSUE TITLE
RetroArch 2048

### ISSUE THREAD

**Issue by IllusionMan1212** [Vita3K/homebrew-compatibility#131]
# Homebrew summary
- VitaDB: https://vitadb.rinnegatamante.it/#/info/215
- Homebrew version: RetroArch 2048 vNightly

# Vita3K summary
- Version: v0.1
- Build number: 113
- Commit hash: 598243c

# Test environment summary
- Tested by: IllusionMan1212
- OS: Windows 10 Pro Fall Creators
- CPU: AMD Ryzen 5 1600
- GPU: NVIDIA GTX 1050Ti
- RAM: 8GB

# Issues
Crashes

# Screenshots
![2048retrolib](https://user-images.githubusercontent.com/36709480/36870881-1cc0b652-1da9-11e8-883b-f7bfaf32c2c7.PNG)

**Comment by nishinji** [comment]
Looks no longer available
