### ISSUE TITLE
ULTIMATE MARVEL VS. CAPCOM 3

### ISSUE THREAD

**Issue by arthas526** [Vita3K/homebrew-compatibility#239]
# Vita3K summary
- Version: v0.1
- Build number: 741-f506355
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 

# Test environment summary
- Tested by: ?
- OS: Windows 10
- CPU: i7-4710m
- GPU: 850m
- RAM: 8 GB

# Issues
Crashes on 

# Screenshots
Not available

# Log
[vita3k.log](https://github.com/Vita3K/homebrew-compatibility/files/2876047/vita3k.log)

**Comment by Zangetsu38** [comment]
I close it, here is for hombrew not for commercial game, go to here for commercial game 
https://github.com/Vita3K/compatibility/issues
