### ISSUE TITLE
System 32bit

### ISSUE THREAD

**Issue by Necron00** [Vita3K/homebrew-compatibility#243]
# Homebrew summary
- VitaDB: <http://vitadb.rinnegatamante.it/#/info/?>
- Homebrew version: v?

# Vita3K summary
- Version: v?
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 

# Test environment summary
- Tested by: ?
- OS: Windows 7
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 1 GB

# Issues

# Screenshots
![](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Zangetsu38** [comment]
What is that ?
