### ISSUE TITLE
Grand Theft Auto: San Andreas [GTASA0000]

### ISSUE THREAD

**Issue by benjamintoledo** [Vita3K/homebrew-compatibility#261]
# Homebrew summary
- VitaDB: https://vitadb.rinnegatamante.it/#/info/618
- Title ID: 618
- Homebrew version: 2.1

# Vita3K summary
- Version: 0.2.0
- Build number: 3565
- Commit hash: Unsure
- CPU backend:Dynarmic.
- GPU backend: AMD Radeon(TM) Graphics

# Test environment summary
- Tested by: benjamintoledo
- OS: Windows 11
- CPU: AMD Ryzen 5 4600G
- GPU:  AMD Ryzen 5 4600G
- RAM: 16 GB

# Issues
- It needs taiHEN, ux0 and other plugins so it gives error during launching

# Screenshots
![imagen_2024-02-04_164556665](https://github.com/Vita3K/homebrew-compatibility/assets/158788608/fcbee5e3-4f13-48cf-8086-bb2fd81ff68c)

# Log
[vita3k.log](https://github.com/Vita3K/homebrew-compatibility/files/14158060/vita3k.log)

# Recommended labels
- Nothing

**Comment by bookmist** [comment]
Install libShaccCg as described here https://github.com/AnimMouse/SceShaccCg Installation path for Vita3K is [Pref path]/ur0/data/
[Pref path] could be found in menu file/Open Pref path

**Comment by benjamintoledo** [comment]
> Install libShaccCg as described here https://github.com/AnimMouse/SceShaccCg Installation path for Vita3K is [Pref path]/ur0/data/ [Pref path] could be found in menu file/Open Pref path

I don't know how to install it on Vita3K. I tried and it still failing.
