### ISSUE TITLE
Grand Theft Auto: Chinatown Wars [GTACTW000]

### ISSUE THREAD

**Issue by benjamintoledo** [Vita3K/homebrew-compatibility#262]
# Homebrew summary
- VitaDB: http://vitadb.rinnegatamante.it/#/info/625
- Title ID: 625
- Homebrew version: 1.2

# Vita3K summary
- Version: 0.2.0
- Build number: 3566
- Commit hash: Unsure
- CPU backend: Dynarmic
- GPU backend: AMD Radeon(TM) Graphics

# Test environment summary
- Tested by: benjamintoledo
- OS: Windows 11
- CPU: AMD Ryzen 5 4600G
- GPU: AMD Ryzen 5 4600G
- RAM: 16 GB

# Issues
-Some of the key things to install it like kubridge and FdFix can't be installed in Vita3k as far as I know, so it automatically freezes

# Screenshots
![imagen_2024-02-06_023043805](https://github.com/Vita3K/homebrew-compatibility/assets/158788608/97fe5821-631c-4be2-9f1b-8b92a91b3804)

# Log
[vita3k.log](https://github.com/Vita3K/homebrew-compatibility/files/14175092/vita3k.log)

# Recommended labels
- Crashes
- Unknown

**Comment by nishinji** [comment]
you can get libshacccg from vita
