### ISSUE TITLE
Super Mario 64 [PCSE64101]

### ISSUE THREAD

**Issue by benjamintoledo** [Vita3K/homebrew-compatibility#267]
# Homebrew summary
- App name: Super Mario 64 Vita Español
- App serial: PCSE64101
- App version: 0.00

# Vita3K summary
- Version: 0.2.0
- Build number: 3622
- Commit hash: (https://github.com/Vita3K/Vita3K/releases)
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Benjamin Toledo
- OS: Windows 11
- CPU: AMD Ryzen 5 4600G
- GPU: AMD Ryzen 5 4600G integrated graphics
- RAM: 16 GB

# Issues
It crashes automatically

# Log
[vita3k.log](https://github.com/user-attachments/files/16301177/vita3k.log)

# Recommended labels
- Nothing

**Comment by nishinji** [comment]
Install firmware
And nintendo contents are dangerous
