### ISSUE TITLE
PCSX ReARMed Nightly

### ISSUE THREAD

**Issue by Tutankhamun8080** [Vita3K/homebrew-compatibility#31]
# Homebrew summary
- VitaDB: http://vitadb.rinnegatamante.it/#/info/360
- Homebrew version: RetroArch PCSX ReARMed Nightly
 
# Vita3K summary
- Version: v0.1
- Build number: 113
- Commit hash: 598243c
- Download site: https://ci.appveyor.com/project/Vita3K/vita3k/branch/master/artifacts

# Test environment summary
- Tested by: Tutankhamun8080
- OS: Windows 10 Pro Fall Creators
- CPU: Intel core i7 4930mx @3.1 GHz
- GPU: Nvidia GTX 880m x2 VRAM: 8gb x2 in SLI
- RAM: Dell 16gb DDR3-1600 MHz SODIMM

# Issues
- Crashes.

# Screenshots
![screenshot 205](https://user-images.githubusercontent.com/14711758/36063525-9e087f94-0e43-11e8-9347-e3b975a4a51b.jpg)

**Comment by nishinji** [comment]
Not available now
