### ISSUE TITLE
Bernard Chronicles

### ISSUE THREAD

**Issue by Tutankhamun8080** [Vita3K/homebrew-compatibility#47]
# Homebrew summary
- VitaDB: http://www.psx-place.com/threads/bernard-chronicles-tetris-attack-clone-v-0-01-by-flappy-jesus.11178/
- Homebrew version: v 0.01

# Vita3K summary
- Version: v0.1
- Build number: 113
- Commit hash: 598243c
- Download site: https://ci.appveyor.com/project/Vita3K/vita3k/branch/master/artifacts

# Test environment summary
- Tested by: Tutankhamun8080
- OS: Windows 10 Pro Fall Creators
- CPU: Intel core i7 4930mx @3.1 GHz
- GPU: Nvidia GTX 880m x2 VRAM: 8gb x2 in SLI
- RAM: Dell 16gb DDR3-1600 MHz SODIMM

# Issues
- None, playable

# Screenshots
![screenshot 312](https://user-images.githubusercontent.com/14711758/36498331-98ec21f0-1703-11e8-86ea-b4ad1ced36f5.jpg)

**Comment by nishinji** [comment]
no longer available
(plz open new issue with new link)
