### ISSUE TITLE
Sudorku

### ISSUE THREAD

**Issue by cybertronicgames** [Vita3K/homebrew-compatibility#71]
# Homebrew summary
- VitaDB: https://github.com/dragaron/Sudorku/releases
- Homebrew version: Sudorku
- Info: http://wololo.net/2017/12/09/sudorku-psvita-released-excellent-port-sudoku-vita-touch-controls/ 

# Vita3K summary
- Version: v0.1
- Build number: 54
- Commit hash: 32aa435
- Download site: https://ci.appveyor.com/project/Vita3K/vita3k/branch/master/artifacts

# Test environment summary
- Tested by: Cybertronicgames
- OS: Windows 10 Pro Fall Creators
- CPU: Intel core i7 4930mx @3.1 GHz
- GPU: Nvidia GTX 880m x2 VRAM: 8gb x2 in SLI
- RAM: Dell 16gb DDR3-1600 MHz SODIMM

# Issues
- Crashes.

# Screenshots
![screenshot 205](https://user-images.githubusercontent.com/14711758/36051125-ad5df6b2-0dae-11e8-911d-85324924626d.jpg)

**Comment by Zangetsu38** [comment]
Fail, absolutely not playable :), Only intro. i have already explain that on dev

**Comment by cybertronicgames** [comment]
@Zangetsu38 Oops! My bad. Thanks for fixing that for me.
