### ISSUE TITLE
RetroArch DOSBox

### ISSUE THREAD

**Issue by IllusionMan1212** [Vita3K/homebrew-compatibility#96]
# Homebrew summary
- VitaDB: https://vitadb.rinnegatamante.it/#/info/221
- Homebrew version: RetroArch DOSBox vNightly

# Vita3K summary
- Version: v0.1
- Build number: 113
- Commit hash: 598243c
- Download Site: https://ci.appveyor.com/project/Vita3K/vita3k/branch/master/artifacts

# Test environment summary
- Tested by: IllusionMan1212
- OS: Windows 10 Pro Fall Creators
- CPU: AMD Ryzen 5 1600
- GPU: NVIDIA GTX 1050Ti
- RAM: 8GB

# Issues
Crashes

# Screenshots
![dosbox](https://user-images.githubusercontent.com/36709480/36570176-74993d2e-1839-11e8-873e-82623d2cef00.PNG)

**Comment by nishinji** [comment]
No longer available
